package org.korhan.distile.acceptance;

import org.korhan.distile.demo.LogSimulator;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;

import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

/**
 * End-to-end acceptance test for distile's core promise — <em>"distil thousands of noisy log
 * lines down to their essence."</em> Unlike {@code ExplosionGuardrailTest} (which drives the
 * {@code DrainTree} library directly), this exercises the <b>shipped artifact</b>: it spawns the
 * real fat JAR ({@code target/distile.jar}) as a subprocess via {@code java -jar}, exactly as the
 * {@code ./distile} launcher does, and asserts on its stdout.
 *
 * <p><b>Deterministic input.</b> The stream is generated by the existing {@link LogSimulator} with
 * a fixed {@code --seed}, which makes the output byte-for-byte reproducible: the seed drives the
 * single {@code Random} (every variable part and the PID) and switches timestamps to a synthetic
 * clock, so nothing on the content path reads wall-clock. We materialize the stream to a file
 * first and feed it via stdin redirection — never a live {@code logsim | distile} pipe, whose
 * early-pipe-close behavior would truncate the stream nondeterministically.
 *
 * <p><b>Invariant assertions, not golden output.</b> We assert the distillation properties (bounded
 * template count, the expected distilled templates with {@code <*>} wildcards present, hot patterns
 * dominant by count, rare events surfacing as outliers) rather than exact bytes — robust to
 * cosmetic formatting changes, yet failing hard if the tool ever stops distilling.
 *
 * <p>Named {@code *IT} so it runs under maven-failsafe in the {@code verify} phase (after the JAR
 * is packaged), not under surefire. Skips gracefully (via {@code assumeTrue}) if the JAR is absent,
 * e.g. when run from an IDE without a prior {@code mvn package}.
 */
class DistilesSpringBootStreamIT {

    /** Same path the ./distile launcher uses; Maven runs tests with the module dir as cwd. */
    private static final Path JAR = Paths.get("target", "distile.jar");

    private static final long SEED = 42L;
    private static final int LINES = 5000;

    private static Path fixture;

    @BeforeAll
    static void generateSeededFixture() throws Exception {
        assumeTrue(Files.isRegularFile(JAR),
                () -> "fat JAR not built at " + JAR.toAbsolutePath() + " — run `mvn package` or `mvn verify`");

        fixture = Files.createTempFile("distile-e2e-", ".log");
        // Reuse LogSimulator as the single source of truth for the scenario. Redirect its stdout
        // to the fixture file; --rate 0 emits as fast as possible, --seed makes it reproducible.
        PrintStream original = System.out;
        try (PrintStream ps = new PrintStream(Files.newOutputStream(fixture), false, StandardCharsets.UTF_8)) {
            System.setOut(ps);
            LogSimulator.main(new String[]{
                    "--seed", Long.toString(SEED), "--count", Integer.toString(LINES), "--rate", "0"});
            ps.flush();
        } finally {
            System.setOut(original);
        }
        assertTrue(Files.size(fixture) > 0, "fixture generation produced no output");
    }

    @AfterAll
    static void cleanup() throws Exception {
        if (fixture != null) {
            Files.deleteIfExists(fixture);
        }
    }

    @Test
    @Timeout(30)
    void distillsSeededSpringBootStreamIntoBoundedTemplateSet() throws Exception {
        // --depth 9 reaches past Spring Boot's fixed 7-token prefix so events separate by message.
        // --snapshot-interval 0 disables the timer thread (the only nondeterministic emission),
        // leaving the FINAL report (fired on EOF) as a stable assertion target.
        // --outlier-max 50: on a 5000-line run the weight-1 events accumulate to counts of ~3-12,
        // well above the default outlier threshold of 2 but far below the hottest real template
        // (200+), so 50 is a wide, seed-stable margin that surfaces them in the outlier view.
        String out = runDistile(fixture,
                "--depth", "9", "--snapshot-interval", "0", "--outlier-max", "50");

        // 1. Collapse happened, and did not over-merge. LogSimulator defines 11 hot + 3 rare shapes;
        //    the 4 HTTP methods split the request line into 4 templates => ~14. A two-sided band
        //    catches both explosion (masking/threshold regressions) and over-collapse.
        int templateCount = finalTemplateCount(out);
        assertTrue(templateCount >= 10 && templateCount <= 16,
                "expected a small bounded template set (10..16), got " + templateCount + "\n" + out);

        // 2. The right distilled templates emerged (stable substrings of the masked forms).
        assertContains(out, "Completed <*> <*>");                                  // request completion
        assertContains(out, "parameters={masked}");                                // MVC request dispatch
        assertContains(out, "Pool stats (total=<*>, active=<*>, idle=<*>, waiting=<*>)"); // HikariCP
        assertContains(out, "from orders o1_<*> where o1_<*>.id=?");               // Hibernate SQL
        assertContains(out, "Created order <*> for customer <*>");                 // app logger

        // 3. New-template events were emitted (the "what's new" emission layer) and the FINAL fired.
        assertContains(out, "[NEW");
        assertContains(out, "[FINAL");

        // 4. Hot patterns dominate: the top template aggregated hundreds of lines rather than
        //    fragmenting. (Guards against a masking regression that would spread one event across
        //    many low-count templates.)
        int topCount = maxTemplateCount(out);
        assertTrue(topCount > 100, "expected a dominant hot template (>100), got " + topCount + "\n" + out);

        // 5. Rare events surfaced in the outlier view, and none of the hot templates leaked into it.
        Matcher m = Pattern.compile("outliers \\(count <= threshold\\): (\\d+)").matcher(out);
        assertTrue(m.find(), "final report missing the outlier section\n" + out);
        assertTrue(Integer.parseInt(m.group(1)) >= 1,
                "expected at least one outlier at --outlier-max 50\n" + out);
        assertContains(out, "Tomcat started on port <*> (http) with context path '/'");
    }

    /**
     * Smoke test of the exact {@code tail -f app.log | distile} stdin/EOF path on a minimal input:
     * a new-template event and a final report must appear, and the process must exit cleanly on EOF.
     */
    @Test
    @Timeout(30)
    void stdinPipeEmitsNewTemplateAndFinalReport() throws Exception {
        Path tiny = Files.createTempFile("distile-e2e-tiny-", ".log");
        try {
            Files.write(tiny, List.of(
                    "Order 123 created for customer 7",
                    "Order 456 created for customer 8",
                    "Order 789 created for customer 9",
                    "User alice logged in from 10.0.0.1"));

            String out = runDistile(tiny, "--snapshot-interval", "0");

            assertContains(out, "[NEW");
            assertContains(out, "[FINAL");
            // The three Order lines share every leading token; only the numbers vary, so they mask
            // to <*> and collapse into ONE template with count 3 — the distillation in miniature.
            assertContains(out, "Order <*> created for customer <*>");
            // Masking also fires on the login line's IP (constant leading tokens, IPv4 -> <*>).
            assertContains(out, "User alice logged in from <*>");
        } finally {
            Files.deleteIfExists(tiny);
        }
    }

    // --- helpers -------------------------------------------------------------

    /** Spawn the real JAR with {@code input} as stdin, return merged stdout+stderr, assert clean exit. */
    private static String runDistile(Path input, String... args) throws Exception {
        List<String> cmd = new ArrayList<>();
        cmd.add(Paths.get(System.getProperty("java.home"), "bin", "java").toString());
        cmd.add("-jar");
        cmd.add(JAR.toString());
        cmd.addAll(Arrays.asList(args));

        Process p = new ProcessBuilder(cmd)
                .redirectInput(input.toFile())   // no file arg => distile reads stdin (the pipe path)
                .redirectErrorStream(true)
                .start();

        // readAllBytes blocks until the process closes stdout (i.e. exits), so this both drains the
        // output and waits for completion; the @Timeout on the test is the wall-clock backstop.
        String out = new String(p.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
        boolean exited = p.waitFor(25, TimeUnit.SECONDS);
        if (!exited) {
            p.destroyForcibly();
            throw new AssertionError("distile did not exit within 25s\n" + out);
        }
        assertEquals(0, p.exitValue(), () -> "distile should exit cleanly on EOF; output:\n" + out);
        return out;
    }

    private static int finalTemplateCount(String out) {
        Matcher m = Pattern.compile("\\[FINAL\\s+\\S+\\]\\s+(\\d+)\\s+templates").matcher(out);
        assertTrue(m.find(), "could not find the FINAL lead line in output:\n" + out);
        return Integer.parseInt(m.group(1));
    }

    /** Largest count across all FINAL table rows ({@code "%8d  #<id>  <template>"}). */
    private static int maxTemplateCount(String out) {
        Matcher m = Pattern.compile("(?m)^\\s*(\\d+)\\s+#\\d+\\s+").matcher(out);
        int max = -1;
        while (m.find()) {
            max = Math.max(max, Integer.parseInt(m.group(1)));
        }
        assertTrue(max >= 0, "no template rows found in output:\n" + out);
        return max;
    }

    private static void assertContains(String haystack, String needle) {
        assertTrue(haystack.contains(needle), "expected output to contain: " + needle + "\n---\n" + haystack);
    }
}
